### ISSUE TITLE
Help with installation and first steps

### ISSUE THREAD

**Issue by k00ni** [balhoff/whelk#217]
I am conducting a survey on OWL reasoners still usable in 2023. For that I would like to try out your reasoner, but having problems with the installation already. Can you give me a short overview how to install/setup the reasoner? Also a mini-example or hint for a small test would be great.

Thanks for your time.

**Comment by balhoff** [comment]
Hi, generally Whelk is used programmatically, either directly from Scala or via its OWL API OWLReasoner interface in Java. You can use it to classify an ontology by running ROBOT: http://robot.obolibrary.org/reason

`robot reason --input ontology.owl --reasoner whelk --output classified.owl`

Whelk is actively developed; I use it in https://github.com/INCATools/relation-graph and https://github.com/balhoff/materializer. For comparing to other OWL reasoners I think it's important to keep in mind its particular performance characteristics (mainly I compare it to ELK, since it is partially based on the same algorithm):
- it is quite a bit slower than ELK for the main task of classifying an ontology
- after finishing classification, it is quite a bit faster than ELK for answering DL queries (and can do so in parallel)
- it can materialize object property assertions, which ELK doesn't do, and supports some of OWL RL and SWRL

There is also a Protege plugin, available here: https://github.com/balhoff/whelk/releases/tag/v1.1.1

You can run a demo of the compiled-to-Javascript version here: https://balhoff.github.io/whelk-web/

I'm happy to answer any other questions!

**Comment by k00ni** [comment]
Many thanks @balhoff, your feedback helps a lot.That is more than enough for the Whelk-part of the survey.

---

Its off topic, but I would like to hear your opinion on the following question: What are your thoughts about the state of OWL reasoners today? State in regards to 
* (code/project) maintenance, 
* accessibility for new users (especially non-programmers), 
* documentation (user guides, setup/installation manuals)
* and support for modern operation systems.

**Comment by balhoff** [comment]
@k00ni sorry, I forgot to reply here. My impression is that many OWL reasoners are barely maintained, if at all. Few have become community-developed open source projects, and are pretty dependent on their original developers to make fixes or changes. I suppose this is because they are pretty complicated codebases. I think most reasoners that are available as Protege plug-ins are pretty accessible to users who are OWL experts. There are also several available within the ROBOT command-line tool. I haven't looked much at reasoner documentation; mainly it helps to know what OWL profile is supported. Most of the reasoners I use are Java-based and work fine on modern operating systems.

**Comment by k00ni** [comment]
Thank you @balhoff!
